name: FBCSP
channels:
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.6.20
  - cycler=0.10.0
  - freetype=2.10.2
  - intel-openmp=2019.4
  - joblib=0.15.1
  - kiwisolver=1.2.0
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - llvm-openmp=10.0.0
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pip=20.1.1
  - pyparsing=2.4.7
  - python=3.8.3
  - python-dateutil=2.8.1
  - readline=8.0
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.32.3
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - mne==0.20.7